apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: dev-app-taxi-taxi-binding
  namespace: cicd
spec:
  params:
  - name: imageRepo
    value: image-registry.openshift-image-registry.svc:5000/wtam/taxi
  - name: tlsVerify
    value: "false"
status: {}
