apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == '<your organization>/gitops')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - name: dev-app-taxi-taxi-binding
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-dev-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == '<your organization>/taxi')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
  - bindings:
    - name: github-push-binding
    interceptors:
    - github:
        secretRef:
          namespace: cicd
          secretKey: webhook-secret-key
          secretName: webhook-secret-new-env-bus
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == '<your organization>/bus')
        overlays:
        - expression: split(body.ref,'/')[2]
          key: ref
    name: app-ci-build-from-push-bus
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
