apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cicd-app
  namespace: argocd
spec:
  destination:
    namespace: demo-cicd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: EventListener
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerTemplate
  - group: triggers.tekton.dev
    jsonPointers:
    - /status
    kind: TriggerBinding
  - group: route.openshift.io
    jsonPointers:
    - /spec/host
    kind: Route
  project: default
  source:
    path: config/demo-cicd/overlays
    repoURL: https://github.com/ishitasequeira/gitops166.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
